// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLmusTuSbXsPcxEkomM1WKMJWSm_ywptA',
    appId: '1:575282180618:web:2a41899ea3fe1ba2dae5f3',
    messagingSenderId: '575282180618',
    projectId: 'fir-eztour',
    authDomain: 'fir-eztour.firebaseapp.com',
    databaseURL: 'https://fir-eztour-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-eztour.appspot.com',
    measurementId: 'G-FY4H6YF0VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClVfI6uCX2oxZXltZ63QhL31qZ8lgXcKE',
    appId: '1:575282180618:android:1bdbb12c32caf95adae5f3',
    messagingSenderId: '575282180618',
    projectId: 'fir-eztour',
    databaseURL: 'https://fir-eztour-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-eztour.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSnlTgyqPdZPMDodBLp_MHtnFJPmUYIKs',
    appId: '1:575282180618:ios:467e747169faf148dae5f3',
    messagingSenderId: '575282180618',
    projectId: 'fir-eztour',
    databaseURL: 'https://fir-eztour-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-eztour.appspot.com',
    iosBundleId: 'com.example.eztour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSnlTgyqPdZPMDodBLp_MHtnFJPmUYIKs',
    appId: '1:575282180618:ios:467e747169faf148dae5f3',
    messagingSenderId: '575282180618',
    projectId: 'fir-eztour',
    databaseURL: 'https://fir-eztour-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-eztour.appspot.com',
    iosBundleId: 'com.example.eztour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLmusTuSbXsPcxEkomM1WKMJWSm_ywptA',
    appId: '1:575282180618:web:dd77700e8e6982eadae5f3',
    messagingSenderId: '575282180618',
    projectId: 'fir-eztour',
    authDomain: 'fir-eztour.firebaseapp.com',
    databaseURL: 'https://fir-eztour-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-eztour.appspot.com',
    measurementId: 'G-65P93V7QP2',
  );
}
